name: 'CI'

on:
  - pull_request

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v20.17.0

      - name: Install Dependencies
        run: yarn install

      - name: Check ESLint
        run: yarn g:lint

      - name: Check Prettier
        run: yarn g:prettier:check

#      - name: Check Unit Test
#        run: yarn run test
